### ISSUE TITLE
Support tcp turn

### ISSUE THREAD

**Issue by namse** [Atlantis-Software/node-turn#8]
Hi!

As you know, some network doesn't support or drop UDP packet forcely. At that time we need tcp turn server.

Is there any plan to support tcp turn relay server?

**Comment by acondura** [comment]
I've just found your project and wanted to ask some clarifications.
Since node-turn support RFC 5389 (STUN), that means it doesn't support RFC 5766 (TURN), right? I'm interested in using this but it's a bit confusing when you say it supports RFC 5389 and above that you say "Node-turn is a STUN/TURN server". I've been playing with coturn in the past month and I see much of the settings/configs that I used there so, I'm wondering: is it STUN or can node-turn handle both STUN and TURN?
I'd appreciate some clarification please. Thank you!

**Comment by atiertant** [comment]
this is not planned at this time but we could accept a pull request

**Comment by trickpattyFH20** [comment]
This would be a great feature to have! @atiertant 
Did you have any luck implementing that yourself? @namse

**Comment by trickpattyFH20** [comment]
Are there any specific challenges in implementing support for TCP that are different than the current UDP implementation? @atiertant
